---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quantumrift
  namespace: default
  labels:
    app: quantumrift
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0%
  selector:
    matchLabels:
      app: quantumrift
  template:
    metadata:
      labels:
        app: quantumrift
    spec:
      containers:
      - name: quantumrift
        image: xenozan/quantumrift:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"

            